# Site settings
title = "Vision - FlowIn.Space"
baseurl = "http://flowin.space/vision"
theme = "hugo-agency-theme"
languageCode = "en-US"
publishdir = "public/en"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Vision - Point of Vision"
  description = "A Diego Turtulici's project, born in 2016. Means which frees your creativity and shapes the ideas that reawaken your intuitions. We are continuously stirring and that changes us, inevitably. Our point of view becomes more and more subjective, personal, multifaceted and complex, incoherent and rich of meaning. Point of Vision: a personal perspective which manifests itself as ideal in the idea."

  # Link custom assets relative to /static
  custom_css = ['css/vision.css']
  custom_js  = ['js/vision.js'] #js/pointer_glow.js
  favicon    = "favicon.png"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Damn, something went wrong!"
    text = "Back to [homepage](/)!"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = ".vision"
    # Optional logo as brand stored in img/
    logo = "logo.svg"
    about = "what's vision"
    portfolio = "gallery"
    # contact = "contatta"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "#SenzaParole"
      name = "Senza Parole"
      weight = 1

    [[menu.postpend]]
      url = "http://flowin.space"
      name = "FlowIn.Space"
      weight = 2


  # Hero section
  [params.hero]
    enable = true
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "fluid digital art"
    subtitle = ".vision"
    buttonText = "explore"

  # About section
  [params.about]
    enable = true
    title = "The idea"
    subtitle = "Visions are pure intuitions, means which frees your creativity and shapes the ideas that reawaken your intuitions, here it is born .vision: a Diego Turtulici's project. Our life experiences, those of the ones we cross, with whom we have some sort of relationship, they change, take and give us. We are continuously stirring and that changes us, inevitably. our point of view becomes more and more subjective, personal, multifaceted and complex, incoherent and rich of meaning. So there's the need to tell, comunicate, arouse something in viewers' eyes, something that came from a vision, a point of view, a point of vision: .vision, a personal perspective which manifests itself as ideal in the idea."
    endpoint = "2016"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.

    [[params.about.events]]
      img = "SenzaParole_2329_11_19_hugmilano.png"
      date = "23-29 november 2019"
      title = "[Brilla Speciale Milano Music Week-Indie Beat Generation](https://www.facebook.com/events/1289548541252032/)"
      description = "_SenzaParole_ at [_hug_](https://www.facebook.com/HugMilano) for [_Milano Music Week_](https://www.milanomusicweek.it), Milano."

    [[params.about.events]]
      img = "SenzaParole_29_6_18_serafini.jpg"
      date = "5 july 2019"
      title = "[Senza parole in university](https://www.facebook.com/ArteinUniversita/photos/a.1568226293312438/1575910215877379/)"
      description = "Partecipation and exposition of SenzaParole at 'arte in università' XII edition."

    [[params.about.events]]
      img = "SenzaParole_29_6_18_serafini.jpg"
      date = "29 june 2018"
      title = "[Senza parole in university](https://www.facebook.com/events/397455927335551)"
      description = "Partecipation and exposition of SenzaParole at 'arte in università'. XI edition."

    [[params.about.events]]
      img = "SenzaParole_17_6_18_nicaragua.jpg"
      date = "17 june 2018"
      title = "[Senza parole at Nicaragua](https://www.facebook.com/events/397455927335551)"
      description = "Partecipation at local market Nicaragua in Livorno."

    [[params.about.events]]
      img = "SenzaParole_26_5_18_despisa.jpg"
      date = "26 may 2018"
      title = "[Senza parole at autoproductions' feast](https://www.facebook.com/events/2044153592505113/)"
      description = "Exposition with 'Mercato Contadino di Pisa' in Martiri square."

    [[params.about.events]]
      img = "SenzaParole_1113_08_17_FaroScoglitti.png"
      date = "11-13 agust 2017"
      title = "[Senza parole at piccolo Museo del Mare Faro - Scoglitti](https://www.facebook.com/events/397455927335551)"
      description = "Third exhibition of the illustrations _[Senza Parole](SenzaParole/)_, the first one in Sicily."

    [[params.about.events]]
      img = "SenzaParole_19_5_17_exploit.png"
      date = "19 - 25 maggio 2017"
      title = "[Senza parole @exploit - Pisa](https://www.facebook.com/events/1951071915122550)"
      description = "Second exhibition of the illustrations _[Senza Parole](SenzaParole/)_ at [exploit](https://exploitpisa.org) with music."

    [[params.about.events]]
      img = "SenzaParole_7_4_16_exploit.jpg"
      date = "7 aprile 2016"
      title = "[Senza parole @exploit - Pisa](https://www.facebook.com/events/1592724811018450)"
      description = "Second exhibition of the illustrations _[Senza Parole](SenzaParole/)_ at [exploit](https://exploitpisa.org) with concert by [Lorenzo Niccolini](https://www.facebook.com/circolo.pisano)."



  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Gallery"
    # subtitle = "Lorem ipsum dolor sit amet consectetur."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Tag"
      buttonText = ""

  # SenzaParole section
  [params.senzaparole]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Senza Parole"
    subtitle = "_Senza Parole (Without Words, Speechless)_ Words, that speaks of and to our souls, try to take shape through these illustrations, which don't try to describe their meanings, they're the result of their influences, sensations. Where imagination begins. Where words can't be enough."

    [params.senzaparole.modal]
      client = "Client"
      date = "Date"
      etimo = "Etimo"
      sitePost = "Site"
      category = "Tags"
      buttonText = ""
      video = "Video"

  # Footer section
  [params.footer]
    enable = true
    # copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/pointvision"

    [[params.footer.quicklinks]]
      tag = "hosting"
      text = "eigenLab"
      link = "https://eigenlab.org/"

    [[params.footer.quicklinks]]
      tag = "engine"
      text = "hugo"
      link = "http://gohugo.io/"

    [[params.footer.quicklinks]]
      tag = "theme (base)"
      text = "agency"
      link = "http://themes.gohugo.io/theme/agency/"

    [[params.footer.quicklinks]]
      tag = "source code"
      text = "vision"
      link = "https://git.eigenlab.org/sbiego/vision-hugo"
